export * from "./background";
export * from "./border";
export * from "./color";
export * from "./effect";
export * from "./flexbox";
export * from "./grid";
export * from "./interactivity";
export * from "./layout";
export * from "./list";
export * from "./position";
export * from "./space";
export * from "./text-decoration";
export * from "./transform";
export * from "./transition";
export * from "./typography";
export * from "./scroll";
export type { Config } from "./config";
